stages:
  - prepare
  - check
  - test
  - deploy

variables:
  BUILD_PREREQUISITES_CACHE_KEY: "build_pre_${PHP_DC_DOWNLOAD}"

download_prerequisites:
  image: composer:1.8.0
  stage: prepare
  script:
    - if [ ! -d vendor ] || [ ! -f composer.lock ]; then composer install --ignore-platform-reqs; fi
  cache:
    key: $BUILD_PREREQUISITES_CACHE_KEY
    paths:
      - composer.lock
      - vendor
    policy: pull-push
  tags:
    - docker

check_dependencies:
  image: composer:1.8.0
  stage: check
  script:
    - composer audit
  cache:
    key: $BUILD_PREREQUISITES_CACHE_KEY
    paths:
      - composer.lock
      - vendor
    policy: pull
  tags:
    - docker

check_code_style:
  image: composer:1.8.0
  stage: check
  script:
    - composer cs-fixer-dry
  cache:
    key: $BUILD_PREREQUISITES_CACHE_KEY
    paths:
      - vendor
    policy: pull
  tags:
    - docker

run_unit_tests:
  image: composer:1.8.0
  stage: test
  script:
    - docker-compose up -d php56
    - docker-compose up -d php73
    - echo '******************** Unit Tests PHP 5.6 ********************'
    - docker-compose exec -T php56 php -v
    - docker-compose exec -T php56 composer cover-text
    - echo '******************** Unit Tests PHP 7.3 ********************'
    - docker-compose exec -T php73 php -v
    - docker-compose exec -T php73 composer cover-text
  cache:
    key: $BUILD_PREREQUISITES_CACHE_KEY
    paths:
      - vendor
  tags:
    - docker

run_integration_tests:
  stage: test
  before_script:
    - apk add --no-cache bash curl python3 jq python make g++
    - pip3 install docker-compose==1.23.2 awscli
    - $(aws ecr get-login --region=us-east-1 --no-include-email --registry-ids 602824140852)
  script:
    - cd tools
    - docker-compose down
    - CI_STACK=1 ./initLocalStack.sh
    - echo '******************** Integration Tests PHP 5.6 ********************'
    - docker-compose exec -T php56 php -v
    - docker-compose exec -T php56 composer integration-tests-local
    - echo '******************** Integration Tests PHP 7.3 ********************'
    - docker-compose exec -T php73 php -v
    - docker-compose exec -T php73 composer integration-tests-local
  cache:
    key: $BUILD_PREREQUISITES_CACHE_KEY
    paths:
      - vendor
    policy: pull
  tags:
    - docker
    - ecr

sync_to_github:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client git
    - mkdir ~/.ssh && chmod 0700 ~/.ssh
    - echo "$GITHUB_PK" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - echo "$GITHUB_HK" > ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts
  script:
    - git remote add github git@github.com:shopgate/connect-integration-sdk-php.git || true
    - git checkout master
    - git push github $CI_COMMIT_REF_NAME:master --force
    - git push --tags github
  tags:
    - docker
  when: manual
  only:
    - tags