dist: xenial
sudo: false
language: php

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install

script:
- vendor/bin/phpunit

jobs:
  include:
  - stage: Unit Tests + Code Style Fixing + Code Coverage
    php: '7.3'
    before_script:
    - composer install
    script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - curl -L http://files.shopgate.com/travis-ci/php-cs-fixer-v2.phar -o php-cs-fixer
    - chmod a+x php-cs-fixer
    - git checkout -B $TRAVIS_BRANCH
    - ./php-cs-fixer fix --config=.php-cs.dist --cache-file=.php-cs.cache --diff --dry-run --verbose .
    - rm php-cs-fixer
    after_success:
    - travis_retry php vendor/bin/php-coveralls -v
  - stage: Unit Tests
    php: '5.6'
  - stage: Unit Tests
    php: '7.0'
  - stage: Unit Tests
    php: '7.1'
  - stage: Unit Tests
    php: '7.2'
  - stage: deploy
    php: '5.6'
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then ./release/build_release_package.sh ; fi
    deploy:
      provider: releases
      api_key:
        secure: mT4wgnW0coSA6WFcL6wx7BV6hHn+NOeAF+mWAooyaNHwXAHK4x2y/GVtz4tVZ6QqjGyDYyswWHq0wUt6UWruahX4O59a7X3olECow7aMdt4WsqqzCyAb9uIFr5ELAFvOu8TLNELXIzibkSRckcAWmObtnGg3FpAieOWUBl7IIzR2mGdanYePyjbf3XyoHVuwrBRpdSyMkaduYSE3UwECQp6KglXkxPNKrcgfgOS1Q3ZH6J9PKTiGFe9az5wAoGvbTJyS2AQGf+eHTF2IG4nR1EasUkBLZuEowc3yyJYmyOQb/uupIuI90zFu61+46NY+UjVJvN7rqmZoQ/K9gr2E+nst6kOKbHFLg4unNfOazAd2KSqR8PFaopNThuqd6tKikn7PxcJMDtib2JCLiCZPVno2IEI2nRneKx9E7ii4mTNhOIg3PCJex3SNlj18UGhQyy3Tc1N349M8dsPTpXQlLAIXKIlpDpI+LbMgY7SpqBtrswnZKTIjTQbyipg3vgjxEaOG+fnefRCF+1ZJ/JSl2qfkCWoYaLeCMK6keljVv0DVKZjmOEHvaI24lukpIkBKKhduHuEbfsqWGu5VxFKg6clvJIG0d1TLOjPVW4TWNMAqky6ACrwlVYqSPPgQKVGchkS+l/HzROG3SrhLDeYZCMPnWZHJ9BzgAdxiot8qWyw=
      file: shopgate-cloud-integration-sdk-php.zip
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      secure: "B8bGcKESZAE1dPDpoClVcvsrSHarqgxI8p2Jm09+r1rnarv5YZFiMafb6TkfZf6NQqJ8byoJGeEZLxF50+vd/2GdwACmWi65k0IL+WaPnVbLVno4pW2fRpu0F4tfUhdJuRB2+nJ4sEPujSVVXuN+IIGLe/qPqZ/yvbY3abEza6clGzOTS4SUo+DIwiq9mPCmHIl4bxFGlEVWuy+FqSVEAHI1UHUB0J+UF14r0IULRhG6pA37xWQpBnARjiA6TmITgYrRdfxOr3lO4jAeSgSDhzy9H8wjSy52taLJ/n5NqQ4IO8w2yYYzovWcaQnMT0ElXogkJ2yYasYndp5rb4RcU1/n3XwwgBDPnPFCXxQ4P6Pi4lodH8bf8PHxp1Wey4aI82XkEc6ru0rOI+PDEn7BMdS2zzRh6BBd1mPf24V9EFH0SfpcXtktqgXZZpyYNkm/scL1bbWC8YQFGOIK5y5PnTycV8iacTqUu3N7bHu4Ngf+1DO/SDPM7dk63IJWBMEKGKeDcPW/N4JyLrCQwC2zUu9qhBrioHAiOJ6vluUapMqLjiXOlkQpy53iIkfRDJvjyxxy9ej7EzRxmVslI/hWjdicLFWssEUk5TtV16p7i9zIGrE+8osXlb6zRjmishlw1UV9nNb47Q6JBA+UaK+yZnr+/37OrPtEahYJyXWeFhU="
    on_success: change
    on_failure: always
