dist: xenial
sudo: false
language: php

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install

script:
- vendor/bin/phpunit

jobs:
  include:
  - stage: Unit Tests + Code Coverage
    php: '7.3'
    before_script:
    - composer install
    script:
    - git checkout -B $TRAVIS_BRANCH
    - travis_retry composer coveralls
  - stage: deploy
    php: '5.6'
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then ./release/build_release_package.sh ; fi
    deploy:
      provider: releases
      api_key:
        secure: "cJT+4K8obPbAssLQ9AgRr/5gCdQ+ifsGvzsQFG01vKY0sMNAVk3x41fNeN6TNqchnahzzR/nHsoEZ4qFoHluC1GEKkAv1geIOajPA0wiSUPUfOMXry/187rDGqW2oYe4mAnFUuf+E1K1B6OEdbFBJlNLWAOL9Z+G6xomHNiKyZnjfSuSwe8GgI6fJvSZ56RX1+BfHX27uxHkHhge99t1qKJUI85PsVyljLGQjGfEFy53HifyBS5wlMHvsqT7BG2w1D4GXjzGzGDTyKiOhKTbIrOZqkT5EaU0C3nUeF3eq71Uo/ct0Xd9fe53i2qSh6wLKDP09h5roh2xh5RR6+7pg6YzlxALRNAS3QjKSnStFWr7dhelAsy8vcWTZePmLpzQrqbGxY6W7nwFBNOZHJ/Dy7yVoM1hG6JfOhJjxRgELg9NVfuRL24zkznHO4pjaqgknlJSWR4ntpwrvVciem7hXMOkdS9V9MBBJlHCd+Z416yYrBrSM/JhLjXprVY1mGaITM8865N2SRMx5N0We/SzCiQ60SRnbyLuSXZWJL5ZSYm24ZbzIPm6jGVObzE7pU3ER17XY5Tir119CcMeJ0ZEVv4mnoo6oS1aGxiJnczpRBqi/lXcR1gkvho3iyzMT3f7mTkxt4d+jTX6Z6Q0YY9FRCsVJ/X8MKp7nZ9wdlDyC+s="
      file: shopgate-cloud-integration-sdk-php.zip
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      secure: "B8bGcKESZAE1dPDpoClVcvsrSHarqgxI8p2Jm09+r1rnarv5YZFiMafb6TkfZf6NQqJ8byoJGeEZLxF50+vd/2GdwACmWi65k0IL+WaPnVbLVno4pW2fRpu0F4tfUhdJuRB2+nJ4sEPujSVVXuN+IIGLe/qPqZ/yvbY3abEza6clGzOTS4SUo+DIwiq9mPCmHIl4bxFGlEVWuy+FqSVEAHI1UHUB0J+UF14r0IULRhG6pA37xWQpBnARjiA6TmITgYrRdfxOr3lO4jAeSgSDhzy9H8wjSy52taLJ/n5NqQ4IO8w2yYYzovWcaQnMT0ElXogkJ2yYasYndp5rb4RcU1/n3XwwgBDPnPFCXxQ4P6Pi4lodH8bf8PHxp1Wey4aI82XkEc6ru0rOI+PDEn7BMdS2zzRh6BBd1mPf24V9EFH0SfpcXtktqgXZZpyYNkm/scL1bbWC8YQFGOIK5y5PnTycV8iacTqUu3N7bHu4Ngf+1DO/SDPM7dk63IJWBMEKGKeDcPW/N4JyLrCQwC2zUu9qhBrioHAiOJ6vluUapMqLjiXOlkQpy53iIkfRDJvjyxxy9ej7EzRxmVslI/hWjdicLFWssEUk5TtV16p7i9zIGrE+8osXlb6zRjmishlw1UV9nNb47Q6JBA+UaK+yZnr+/37OrPtEahYJyXWeFhU="
    on_success: change
    on_failure: always
