version: '2.1'
services:
  php:
    build:
      context: ../
      dockerfile: tools/dockerfiles/Php7
    environment:
      - ETCD_HOST=http://etcd:2379
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
    volumes:
      - ../composer.json:/sdk/composer.json
      - ../phpunit.xml.dist:/sdk/phpunit.xml.dist
      - ../src:/sdk/src
      - ../tests:/sdk/tests
      - ../tools:/sdk/tools
      - ../tools/fixtures/env:/sdk/tests/Integration/.env
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - ${EXPOSED_PORT_MYSQL}:3306

  auth:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/auth2:2018-02-12_48
    restart: always
    links:
      - etcd
      - redis
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - MANAGEMENT_PORT=81
      - LOG_TO_SYSLOG=false
    ports:
      - ${EXPOSED_PORT_AUTH}:80
    networks:
      default:
        aliases:
          - auth.shopgatedev.services
          - omni-merchant.shopgatedev.services
          - omni-location.shopgatedev.services
          - omni-event-receiver.shopgatedev.services
          - catalog.shopgatedev.services