version: '2.1'
networks:
  default:
    external:
      name: sdk-integration-network
services:

### PHP containers for local testing
  php56:
    build:
      context: ../
      dockerfile: tools/dockerfiles/Php56
    environment:
      - ETCD_HOST=http://etcd:2379
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
    tty: true

  php73:
    build:
      context: ../
      dockerfile: tools/dockerfiles/Php73
    tty: true

### infra-structure
  etcd:
    image: elcolio/etcd
    restart: always
    environment:
      - 'ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://etcd:4001'

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  redis:
    image: library/redis

  auth:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/auth2:2018-02-12_48
    restart: always
    links:
      - etcd
      - redis
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - MANAGEMENT_PORT=81
      - LOG_TO_SYSLOG=false
    networks:
      default:
        aliases:
          - auth.shopgatedev.services
          - omni-merchant.shopgatedev.services
          - omni-location.shopgatedev.services
          - omni-customer.shopgatedev.services
          - omni-event-receiver.shopgatedev.services
          - catalog.shopgatedev.services
          - import.shopgatedev.services

  googlepubsub-emulator:
    build:
      context: ./dockerfiles
      dockerfile: GooglePubsub

### services

### https://gitlab.localdev.cc/omnichannel/services/worker
  omni-worker:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/worker:v1.0.0-beta.10c
    ports:
      - 5100:80
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085

### https://gitlab.localdev.cc/omnichannel/services/event-receiver
  omni-event-receiver:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/event-receiver:v1.0.0-beta.11
    ports:
      - 5101:80
    restart: always
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085

### https://gitlab.localdev.cc/omnichannel/services/merchant
  omni-merchant:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/merchant:v1.0.0-beta.14
    ports:
      - 5102:80
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

### https://gitlab.localdev.cc/omnichannel/services/location
  omni-location:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/location:v1.0.0-alpha.33
    ports:
      - 5103:80
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

  omni-customer:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/customer:v1.0.0-alpha.28
    restart: always
    environment:
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
    links:
      - etcd

  ### https://gitlab.localdev.cc/omnichannel/services/products
  catalog:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/catalog:v1.0.0-alpha.69
    ports:
      - 5104:80
    restart: always
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

  s3:
    image: lphoward/fake-s3
    ports:
      - '4569:4569'
    networks:
      default:
        aliases:
          - shopgate-import.s3

  ### https://gitlab.localdev.cc/big-api/services/import
  import:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/import:v1.0.0-alpha.3
    ports:
      - 5105:80
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_BUCKET_NAME=shopgate-import
      - AWS_REGION=eu-central-1
      - AWS_S3_ENDPOINT=http://s3:4569
      - GITLAB_IMPORT_WEBHOOK_URL=https://webhook.site/476d03a0-882a-469c-9189-0168aa55617f
      - GITLAB_TOKEN=bar
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
    links:
      - etcd
