version: '2.1'
services:

  ### PHP containers for local testing
  php56:
    build:
      context: ../
      dockerfile: tools/dockerfiles/Php56
    environment:
      - ETCD_HOST=http://etcd:2379
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
    tty: true

  php73:
    build:
      context: ../
      dockerfile: tools/dockerfiles/Php73
    tty: true

  ### infra-structure
  etcd:
    image: elcolio/etcd
    restart: always
    environment:
      - 'ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://etcd:4001'

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  ### https://gitlab.localdev.cc/omnichannel/services/auth
  omni-auth:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/auth:v1.0.0-beta.7
    restart: always
    links:
      - etcd
      - sqs
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - MANAGEMENT_PORT=81
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
    networks:
      default:
        aliases:
          - omni-auth.shopgatedev.io
          - omni-merchant.shopgatedev.io
          - omni-location.shopgatedev.io
          - omni-customer.shopgatedev.io
          - omni-event-receiver.shopgatedev.io
          - catalog.shopgatedev.io
          - import.shopgatedev.io
          - omni-order.shopgatedev.io
          - user.shopgatedev.io

  googlepubsub-emulator:
    build:
      context: ./dockerfiles
      dockerfile: GooglePubsub

  sqs:
    image: pafortin/goaws

  ### services

  ### https://gitlab.localdev.cc/omnichannel/services/user
  user:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/user:v1.0.0-beta.37
    restart: always
    links:
      - etcd
    environment:
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
      - INTEGRATION=1

  ### https://gitlab.localdev.cc/omnichannel/services/worker
  omni-worker:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/worker:v1.0.0-alpha.21
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
      - QUEUE_BATCH_SIZE=100
      - QUEUE_BATCH_DELAY=50

  ### https://gitlab.localdev.cc/omnichannel/services/event-receiver
  omni-event-receiver:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/event-receiver:v1.0.0-beta.14
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085

  ### https://gitlab.localdev.cc/omnichannel/services/merchant
  omni-merchant:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/merchant:v1.0.0-beta.14
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

  ### https://gitlab.localdev.cc/omnichannel/services/location
  omni-location:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/location:v1.0.0-alpha.51
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

  ### https://gitlab.localdev.cc/omnichannel/services/customer
  omni-customer:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/omni/customer:v1.0.0-alpha.31
    restart: always
    environment:
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
    links:
      - etcd

### https://gitlab.localdev.cc/omnichannel/services/order
  omni-order:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/omni/order:v1.0.0-beta.116
    restart: always
    environment:
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
    links:
      - etcd

  elasticsearch:
    image: elasticsearch:6.8.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false

  ### https://gitlab.localdev.cc/omnichannel/services/products
  catalog:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/service/catalog:v1.0.0-alpha.89
    restart: always
    links:
      - etcd
    environment:
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false

  s3:
    image: lphoward/fake-s3
    networks:
      default:
        aliases:
          - shopgate-import.s3
          - shopgate-import.s3.amazonaws.com

  ### https://gitlab.localdev.cc/big-api/services/import
  import:
    image: 602824140852.dkr.ecr.us-east-1.amazonaws.com/development/service/import:v1.0.0-alpha.5
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_BUCKET_NAME=shopgate-import
      - AWS_REGION=eu-central-1
      - AWS_S3_ENDPOINT=http://s3:4569
      - GITLAB_IMPORT_WEBHOOK_URL=http://import-script:8079/
      - GITLAB_TOKEN=bar
      - SYSLOG_LOG_LEVEL=debug
      - NODE_ENV=development
      - APP_PORT=80
      - LOG_TO_SYSLOG=false
    links:
      - etcd

  ### https://gitlab.localdev.cc/SGXS/tools/import-script/tree/development
  import-script:
    build:
      context: ../
      dockerfile: tools/dockerfiles/ImportScript
    environment:
      - APP_PORT=8079
      - S3_SECRET_ACCESS_KEY_ID=foo
      - S3_SECRET_ACCESS_KEY=bar
      - S3_BUCKET=shopgate-import
      - S3_REGION=eu-central-1
      - S3_ENDPOINT=http://s3.amazonaws.com:4569
      - PUBSUB_EMULATOR_HOST=googlepubsub-emulator:8085
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=import
      - GOOGLE_APPLICATION_CREDENTIALS=tools/dockerfiles/credentials-dev.json.js
      - BIG_API_CLIENT_ID=integration-tests
      - BIG_API_CLIENT_SECRET=integration-tests
      - BIG_API_ENDPOINT_SCHEMA=http://{serviceName}.{baseDomain}
      - PUBSUB_PROJECT_ID=test-project
      - PUBSUB_BATCHING={}
      - PUBSUB_TOPIC=entityChanged
    tty: true
    links:
      - s3:s3.amazonaws.com
